#!/usr/bin/env bash
###############################################################################
#  Module: shell.sh
#  Purpose: Shell configuration (zsh)
#  Dependencies: logging.sh, config.sh, homebrew.sh
###############################################################################

set -Eeuo pipefail

# Source dependencies
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/logging.sh"
source "$SCRIPT_DIR/config.sh"
source "$SCRIPT_DIR/homebrew.sh"

###############################################################################
#  Backup Existing Shell Config
#  Usage: backup_existing_config <config_file>
#  Returns: Backup file path or empty string
###############################################################################

backup_existing_config() {
  local config_file="$1"
  
  [[ -z "$config_file" ]] && { log_error "[shell] Config file path required"; echo ""; return; }
  
  if [[ ! -f "$config_file" ]]; then
    # No file to backup
    echo ""
    return 0
  fi
  
  local timestamp
  timestamp=$(date +%Y%m%d_%H%M%S)
  local backup_path="${config_file}.backup.${timestamp}"
  
  if cp "$config_file" "$backup_path"; then
    log_info "[shell] Backed up $config_file to $backup_path"
    echo "$backup_path"
  else
    log_error "[shell] Failed to backup $config_file"
    echo ""
  fi
}

###############################################################################
#  Install Shell Plugin
#  Usage: install_shell_plugin <plugin_name>
#  Returns: 0 on success, 1 on failure
###############################################################################

install_shell_plugin() {
  local plugin_name="$1"
  
  [[ -z "$plugin_name" ]] && { log_error "[shell] Plugin name required"; return 1; }
  
  log_info "[shell] Installing shell plugin: $plugin_name"
  
  # Check if plugin is available via Homebrew
  if is_homebrew_installed; then
    # Try to install via Homebrew first
    if brew list "$plugin_name" &> /dev/null || install_package "$plugin_name" "formula"; then
      log_success "[shell] Installed plugin $plugin_name via Homebrew"
      return 0
    fi
  fi
  
  # For oh-my-zsh plugins, they're typically installed in ~/.oh-my-zsh/custom/plugins
  # This is a simplified implementation
  log_warn "[shell] Plugin installation method not fully implemented for: $plugin_name"
  return 0
}

###############################################################################
#  Generate Zshrc Content
#  Usage: generate_zshrc <theme> <plugins_array> <aliases_hash>
#  Returns: Zshrc content as string
###############################################################################

generate_zshrc() {
  local theme="$1"
  shift
  local plugins=("$@")
  
  # This is a simplified zshrc generator
  # In a full implementation, this would generate a complete .zshrc file
  
  local content=""
  content+="# Generated by macOS Bootstrap Script\n"
  content+="# $(date)\n\n"
  
  # Oh My Zsh setup (if theme/plugins suggest it)
  if [[ -n "$theme" ]] || [[ ${#plugins[@]} -gt 0 ]]; then
    content+="export ZSH=\"\$HOME/.oh-my-zsh\"\n\n"
    
    if [[ -n "$theme" ]]; then
      content+="ZSH_THEME=\"$theme\"\n\n"
    fi
    
    if [[ ${#plugins[@]} -gt 0 ]]; then
      content+="plugins=(\n"
      local plugin
      for plugin in "${plugins[@]}"; do
        content+="  $plugin\n"
      done
      content+=")\n\n"
    fi
    
    content+="source \"\$ZSH/oh-my-zsh.sh\"\n\n"
  fi
  
  # Aliases would be added here
  # This is a placeholder - full implementation would parse aliases from config
  
  echo -e "$content"
}

###############################################################################
#  Configure Shell
#  Usage: configure_shell
#  Returns: 0 on success, 1 on failure
###############################################################################

configure_shell() {
  if ! is_config_loaded; then
    log_error "[shell] Configuration not loaded"
    return 1
  fi
  
  # Check if shell section exists
  if ! has_config_section "shell"; then
    log_info "[shell] No shell configuration, skipping..."
    return 0
  fi
  
  local zshrc_path="$HOME/.zshrc"
  
  # Backup existing .zshrc
  if [[ -f "$zshrc_path" ]]; then
    backup_existing_config "$zshrc_path" > /dev/null || {
      log_warn "[shell] Backup failed, but continuing..."
    }
  fi
  
  # Get shell configuration
  local theme
  theme=$(get_config_value "shell.theme" "")
  
  # Get plugins (simplified - would need yq for full array parsing)
  local plugins_str
  plugins_str=$(get_config_value "shell.plugins" "")
  
  # Install plugins if specified
  if [[ -n "$plugins_str" ]]; then
    log_info "[shell] Installing shell plugins..."
    # Plugin installation would be handled here
    # This is simplified - full implementation would parse plugin array
  fi
  
  # Generate and write .zshrc
  log_info "[shell] Generating .zshrc..."
  
  # For now, just log that configuration would be applied
  # Full implementation would generate complete .zshrc
  log_info "[shell] Shell configuration would be applied here"
  log_warn "[shell] Full shell configuration requires yq for array parsing"
  
  return 0
}

