#!/usr/bin/env bash
###############################################################################
#  Module: shell.sh
#  Purpose: Shell configuration (zsh)
#  Dependencies: logging.sh, config.sh, homebrew.sh
###############################################################################

set -Eeuo pipefail

# Source dependencies
LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$LIB_DIR/logging.sh"
source "$LIB_DIR/config.sh"
source "$LIB_DIR/homebrew.sh"

###############################################################################
#  Backup Existing Shell Config
#  Usage: backup_existing_config <config_file>
#  Returns: Backup file path or empty string
###############################################################################

backup_existing_config() {
  local config_file="$1"
  
  [[ -z "$config_file" ]] && { log_error "[shell] Config file path required"; echo ""; return; }
  
  if [[ ! -f "$config_file" ]]; then
    # No file to backup
    echo ""
    return 0
  fi
  
  local timestamp
  timestamp=$(date +%Y%m%d_%H%M%S)
  local backup_path="${config_file}.backup.${timestamp}"
  
  if cp "$config_file" "$backup_path"; then
    log_info "[shell] Backed up $config_file to $backup_path"
    echo "$backup_path"
  else
    log_error "[shell] Failed to backup $config_file"
    echo ""
  fi
}

###############################################################################
#  Install Shell Plugin
#  Usage: install_shell_plugin <plugin_name>
#  Returns: 0 on success, 1 on failure
###############################################################################

install_shell_plugin() {
  local plugin_name="$1"
  
  [[ -z "$plugin_name" ]] && { log_error "[shell] Plugin name required"; return 1; }
  
  log_info "[shell] Installing shell plugin: $plugin_name"
  
  # Check if plugin is available via Homebrew
  if is_homebrew_installed; then
    # Try to install via Homebrew first
    if brew list "$plugin_name" &> /dev/null || install_package "$plugin_name" "formula"; then
      log_success "[shell] Installed plugin $plugin_name via Homebrew"
      return 0
    fi
  fi
  
  # For oh-my-zsh plugins, they're typically installed in ~/.oh-my-zsh/custom/plugins
  # This is a simplified implementation
  log_warn "[shell] Plugin installation method not fully implemented for: $plugin_name"
  return 0
}

###############################################################################
#  Generate Zshrc Content
#  Usage: generate_zshrc <theme> <plugins_array> <aliases>
#  Returns: Zshrc content as string
###############################################################################

generate_zshrc() {
  local theme="$1"
  shift
  local plugins=("$@")
  local aliases_str="$*"
  
  # Get Homebrew prefix
  local prefix
  if is_homebrew_installed; then
    prefix=$(brew --prefix)
  else
    log_error "[shell] Homebrew not installed, cannot generate .zshrc"
    return 1
  fi
  
  local content=""
  content+="# Generated by macOS Bootstrap Script\n"
  content+="# $(date '+%Y-%m-%d %H:%M:%S')\n\n"
  
  # Source plugins from Homebrew
  local plugin
  for plugin in "${plugins[@]}"; do
    case "$plugin" in
      zsh-autosuggestions)
        content+="source $prefix/share/zsh-autosuggestions/zsh-autosuggestions.zsh\n"
        ;;
      zsh-syntax-highlighting)
        content+="source $prefix/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh\n"
        ;;
      zsh-history-substring-search)
        content+="source $prefix/share/zsh-history-substring-search/zsh-history-substring-search.zsh\n"
        ;;
    esac
  done
  
  # Initialize completion system
  content+="autoload -U compinit && compinit\n\n"
  
  # Add aliases (handled by caller)
  
  # Add Starship
  content+='eval "$(starship init zsh)"'
  
  echo -e "$content"
}

###############################################################################
#  Configure Shell
#  Usage: configure_shell
#  Returns: 0 on success, 1 on failure
###############################################################################

configure_shell() {
  if ! is_config_loaded; then
    log_error "[shell] Configuration not loaded"
    return 1
  fi
  
  # Check if shell section exists
  if ! has_config_section "shell"; then
    log_info "[shell] No shell configuration, skipping..."
    return 0
  fi
  
  local zshrc_path="$HOME/.zshrc"
  
  # Backup existing .zshrc
  if [[ -f "$zshrc_path" ]]; then
    backup_existing_config "$zshrc_path" > /dev/null || {
      log_warn "[shell] Backup failed, but continuing..."
    }
  fi
  
  # Get shell configuration
  local theme
  theme=$(get_config_value "shell.theme" "")
  
  # Get plugins array
  local plugins
  plugins=$(get_config_array "shell.plugins")
  
  # Convert plugins string to array
  local plugins_array=()
  if [[ -n "$plugins" ]]; then
    read -ra plugins_array <<< "$plugins"
    log_info "[shell] Found ${#plugins_array[@]} plugins: ${plugins_array[*]}"
  fi
  
  # Get aliases from config
  local aliases_content=""
  if has_config_section "shell.aliases"; then
    # Get all alias keys (this requires yq for full support)
    if command -v yq &> /dev/null && [[ -f "$(get_config_file_path)" ]]; then
      local alias_keys
      alias_keys=$(yq eval '.shell.aliases | keys | .[]' "$(get_config_file_path)" 2>/dev/null)
      if [[ -n "$alias_keys" ]]; then
        while IFS= read -r alias_key; do
          local alias_value
          alias_value=$(get_config_value "shell.aliases.$alias_key")
          if [[ -n "$alias_value" ]]; then
            aliases_content+="alias $alias_key='$alias_value'\n"
          fi
        done <<< "$alias_keys"
      fi
    else
      log_warn "[shell] yq not available, aliases from config will be limited"
    fi
  fi
  
  # Generate .zshrc content
  log_info "[shell] Generating .zshrc..."
  
  # Get Homebrew prefix
  local prefix
  if ! is_homebrew_installed; then
    log_error "[shell] Homebrew not installed, cannot configure shell"
    return 1
  fi
  prefix=$(brew --prefix)
  
  # Build .zshrc content
  local zshrc_content=""
  zshrc_content+="# Generated by macOS Bootstrap Script\n"
  zshrc_content+="# $(date '+%Y-%m-%d %H:%M:%S')\n\n"
  
  
  # Source plugins from Homebrew
  local plugin
  for plugin in "${plugins_array[@]}"; do
    case "$plugin" in
      zsh-autosuggestions)
        zshrc_content+="source $prefix/share/zsh-autosuggestions/zsh-autosuggestions.zsh\n"
        ;;
      zsh-syntax-highlighting)
        zshrc_content+="source $prefix/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh\n"
        ;;
      zsh-history-substring-search)
        zshrc_content+="source $prefix/share/zsh-history-substring-search/zsh-history-substring-search.zsh\n"
        ;;
      git)
        # Git plugin is typically part of oh-my-zsh, but we can add git aliases instead
        zshrc_content+="# Git plugin (using aliases instead)\n"
        ;;
    esac
  done
  
  
  # Initialize completion system
  zshrc_content+="autoload -U compinit && compinit\n\n"
  
  # Add aliases
  if [[ -n "$aliases_content" ]]; then
    zshrc_content+="# Aliases\n"
    zshrc_content+="$aliases_content\n"
  fi
  
  # Write .zshrc file
  if echo -e "$zshrc_content" > "$zshrc_path"; then
    log_success "[shell] Generated .zshrc"
  else
    log_error "[shell] Failed to write .zshrc"
    return 1
  fi
  
  # Change shell to zsh if not already
  local current_shell
  current_shell=$(echo "$SHELL")
  local zsh_path
  zsh_path=$(command -v zsh)
  
  if [[ -n "$zsh_path" ]] && [[ "$current_shell" != "$zsh_path" ]]; then
    log_info "[shell] Changing default shell to zsh..."
    if chsh -s "$zsh_path"; then
      log_success "[shell] Default shell changed to zsh (takes effect on next login)"
    else
      log_warn "[shell] Failed to change default shell (may require password)"
    fi
  else
    log_info "[shell] Default shell is already zsh"
  fi
  
  log_success "[shell] Shell configuration completed"
  return 0
}

